[project]
name = "highlights"
version = "0.1.0"
description = "API serving highlighted quotes from books I've read."
readme = "README.md"
authors = [
    { name = "Joe Risner" }
]
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.1",
]

[dependency-groups]
dev = [
    "ruff>=0.11.1",
]

#################
##### Tools #####
#################

[tool.ruff]
indent-width = 4
line-length = 120

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = "dynamic"
indent-style = "space"
quote-style = "double"

[tool.ruff.lint]
# Pyflakes, pycodestyle, flake8-simplify, pyupgrade, pydocstyle
select = ["F", "E", "SIM", "UP"]
