[project]
name = "highlights"
version = "0.1.0"
description = "API serving highlighted quotes from books I've read."
readme = "README.md"
authors = [
    { name = "Joe Risner" }
]
requires-python = ">=3.13"

[dependency-groups]
dev = [
    "ruff>=0.11.1",
]

#################
##### Tools #####
#################

[tool.ruff]
indent-width = 4
line-length = 120

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = "dynamic"
indent-style = "space"
quote-style = "single"

[tool.ruff.lint]
# Pyflakes, pycodestyle, flake8-simplify, pyupgrade
select = ["F", "E", "SIM", "UP"]

[tool.ruff.lint.per-file-ignores]
# Ignore unused imports in __init__.py files
"__init__.py" = ["F401"]
